.gitignore, recipes/minimize_access.rb, spec/recipes/default_spec.rb
Various resources get executed even if there is no change needed. While this is fine it 'pollutes' chef's statistics about updated resources e.g. when someone is monitoring those data using a chef-handler will see changes/updates on each converge:
e.g. within
https://github.com/TelekomLabs/chef-os-hardening/blob/master/recipes/minimize_access.rb
I would probably split "group" and "other"  into separate resources and guard them by "only_if" filters using "find #{folder} -perm -g+w " and "find #{folder} -perm -o+w "
=> Idempotency

recipes/yum.rb
Check to ensure RHN plugin also respects GPG checks.
=> RHN config check should work

COMPLIANCE.md, README.md, TUTORIAL.md, attributes/default.rb, libraries/suid_sgid.rb, recipes/suid_sgid.rb
Having a misspelling in an API is especially awkward, since fixing the spelling could break the code. But I think this is obscure enough that nobody is likely to be using it already...
=> fix SUID/SGID bit cleaning API spelling (unkown -> unknown)

.travis.yml, Gemfile, gemfile.chef-11
- upgrade to berkshelf 4
- fixes #94
Note: Berkshelf 4 dropped Ruby 1.9.3 support
=> Berkshelf 4 Upgrade and Ruby 1.9.3 drop

libraries/apt_package_extras.rb, recipes/apt.rb, recipes/packages.rb
This is to resolve #90 
There are no existing tests for this functionality on the redhat distro family, I haven't added any for the debian family, though in theory a generic test could now be possible.
There is one remaining rubocop warning relating to use of '$/', however this is code taken from the Chef apt package provider (to have consistent behaviour) so I am reluctant to alter this (my regex skills are too weak).
I'd like to make the list of packages to remove an attribute, with the current list as the default. Would that also be an acceptable change? I can add that to to this pull request or pick up separately?
=> Remove packages with known issues on debian/ubuntu

attributes/default.rb, recipes/sysctl.rb, templates/default/rhel_sysconfig_init.erb
Changing settings for SINGLE and PROMPT is required for [CIS 1.5.4 - 1.5.5](https://benchmarks.cisecurity.org/tools2/linux/CIS_Red_Hat_Enterprise_Linux_6_Benchmark_v1.4.0.pdf).  This PR enables these to be set and sets the recommended settings by default.
=> Add SINGLE and PROMPT parameters.

README.md, attributes/default.rb, recipes/apt.rb, recipes/yum.rb
This follows on from my recent pull request for #90 
This exposes the list of packages to be removed by the cookbook as an attribute, with the default value of that attribute preserving the existing behaviour (i.e. creates a customisation point without a breaking change).
My primary reason for exposing this was to allow users of the cookbook to override this list should it be needed (in our specific case, we have an nagios monitoring agent that requires xinetd, which we have then taken further steps to harden) without needing to fork the cookbook.
A secondary reason is that it may make unit testing this functionality (which I am looking at for a subsequent pull request) easier.
I wasn't sure on style for README changes, so welcome any feedback.
=> Expose list of packages to remove as an attribute

attributes/default.rb, recipes/pam.rb, templates/default/rhel_system_auth.erb
This adds adds an attribute for setting pam_cracklib options and fixes #102 related problems.
- Fixed templates not being applied if pam_passwdqc is enabled.
- Install correct package for pam_pwquality in centos 7.
- Add a flag to turn on/off pam_pwquality in rhel7 and set defaults appropriately based on platform_version
- Add an attribute to set options to pam_pwquality.
- Fall back to pam_cracklib on all patforms if neither pam_pwquality nor pam_passwdqc are enabled.
- Don't attempt to install pam_cracklib (It comes with the pam package on rhel 5, 6, & 7)
@chris-rock Please let me know if  you have any feedback about this or any of my other PRs in this repo. :)
=> Pam options and fixes

.kitchen.yml, libraries/suid_sgid.rb, metadata.rb, templates/default/login.defs.erb
* Find was descending into /proc, causing file not found errors and a non-zero return value, causing converge to fail.  This is fixed by using the -prune action to skip recursion into /proc entirely.
* A kitchen configuration for CentOS 5 is added.
=> Initial support for CentOS/RHEL 5

recipes/pam.rb
- missed one attribute namespace pam.rb node['auth']['pam']['passwdqc']['enable']
Fixes https://github.com/dev-sec/chef-os-hardening/issues/118
=> [pam-attr-namespace-fix]

metadata.rb, spec/recipes/login_defs_spec.rb, spec/recipes/sysctl_spec.rb, templates/default/login.defs.erb
Signed-off-by: Patrick Münch <patrick.muench1111@gmail.com>
=> FIX for issue #122 non-ASCII character

.kitchen.vagrant.yml, .kitchen.yml
Added newest OS's for vagrant and dokken.  Most dokken tests fail however due to how docker handles sysctl.
=> Update test-kitchen settings

.kitchen.yml, README.md, metadata.rb, recipes/apt.rb, recipes/yum.rb
The following resources are now completely provided by chef:
- yum_repository
- yum_package
- apt_repository
- apt_package
Currently you get warnings:
```
WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
WARN: Chef::Provider::YumRepository already exists!  Cannot create deprecation class for LWRP provider yum_repository from cookbook yum
WARN: YumRepository already exists!  Deprecation class overwrites Custom resource yum_repository from cookbook yum
```
Starting from the version v12.14.89 the behavior of yum_repository
seems to be the same like in the cookbook before. So I used this …
=> Remove dependenies to apt and yum cookbooks.

.kitchen.yml, README.md, metadata.rb, recipes/apt.rb, recipes/yum.rb
This reverts commit 6e37167db1faa7aca03a78e9c7f8e2d6f79ee55d.
We should use compat_resource if we want compatibility with older chef
versions (<12.14)
Currently I'm running into the following issue https://github.com/chef-cookbooks/compat_resource/issues/122
So I revert the yum/apt dependency removal till it works with
compat_resource
=> Revert "Remove dependenies to apt and yum cookbooks."

.kitchen.yml, README.md, attributes/default.rb, recipes/login_defs.rb, spec/recipes/login_defs_spec.rb, templates/default/login.defs.erb
Adds `node['os-hardening']['auth']['pass_warn_age']` with a default of `7`, and passes it to the `/etc/login.defs` template.
=> Add attribute to control login.defs PASS_WARN_AGE

.kitchen.yml, test/integration/default/controls/tests.rb, test/integration/default/inspec.yml
=> Disable entropy testing

metadata.rb, recipes/sysctl.rb, spec/spec_helper.rb
- removal of deprecations
- fixed the spec tests via generic stub
(was broken on the latest sysctl versions because of native
ruby call File.exist? in the sysctl cookbook)
- enabling the latest sysctl cookbook versions
- fixing the chefspec/fauxhai warnings about platform
=> Cleanup of sysctl dependency

attributes/sysctl.rb, recipes/sysctl.rb, spec/recipes/sysctl_spec.rb
See [this](https://github.com/dev-sec/chef-ssh-hardening/issues/140#issuecomment-267779720) for more details.
CI is red and should get green after #149 is merged and this PR is rebased on top
Review commit-by-commit is a good idea here
=> Moving the attributes with dependencies on other attributes to the recipes

.kitchen.do.local.yml, .kitchen.yml, .travis.yml
=> Chef 13 and 12 CI testing and cleanup of EOL distros

recipes/auditd.rb, spec/recipes/auditd_spec.rb, spec/recipes/default_spec.rb
Fixes GH-145
The new recipe is created with possible assumption, what auditd might get
its configuration later. Besides that, there is no other good place for this
=> Install auditd package

recipes/minimize_access.rb, spec/recipes/minimize_access_spec.rb
on debian /etc/shadow should be readable by shadow group.
This is required by screensavers and similar things
This was also part of https://github.com/dev-sec/linux-baseline/pull/44
=> Proper permissions for shadow on debian family

.kitchen.yml
This is required by https://github.com/dev-sec/linux-baseline/pull/62
=> Proper testing if kernel modules are disabled

attributes/sysctl.rb, metadata.rb
as its enabled per default and can't be switched off
Introduction of temporary version pinning for sysctl cookbook,
see https://github.com/dev-sec/chef-os-hardening/issues/166#issuecomment-322433264
Fixes GH-166
=> Fix: do not touch exec-shield on RHEL 7

.rubocop.yml, README.md, attributes/default.rb, recipes/sysctl.rb, spec/recipes/sysctl_spec.rb, templates/default/filesystem_blacklisting.erb
because of CIS requirement, https://github.com/dev-sec/linux-baseline/pull/71
Fixes #167
=> Lets disable unused filesystems per default

.kitchen.do.local.yml, .kitchen.yml
Lets use the generic centos-7 images on DO, they point
always to the latest distro release
=> Update of testing boxes/images

.kitchen.yml, README.md, attributes/default.rb, recipes/default.rb, recipes/selinux.rb, templates/default/rhel_selinuxconfig.erb, test/integration/default/inspec.yml, test/integration/selinux_enabled/controls/tests.rb, test/integration/selinux_enabled/inspec.yml
lets have an attribute for enforcing or permissiving SELinuxon RHEL/Centos.
Implementation like suggested in issue: https://github.com/dev-sec/chef-os-hardening/issues/106
=> Selinux enforcing support for RHEL/Centos

.kitchen.do.local.yml, .kitchen.yml, .travis.yml
This allows easy usage and testing of different suites locally and in
the CI (DO)
Also updating Fedora platforms. Fedora 24 is EOL.
=> Using the same names for platforms for different drivers

recipes/yum.rb
On Fedora dnf is used and not yum. Lets chef decide which provider to
use
=> Fix: lets use generic package resource

attributes/default.rb, recipes/minimize_access.rb
https://github.com/dev-sec/linux-baseline/pull/82
Its WIP as the linux-baseline PR is not merged yet
=> RH family: adapt some settings, as RH has better defaults

recipes/minimize_access.rb
Ubuntu tests should be fixed once dev-sec/linux-baseline#83 is merged.
CC @artem-sidorenko
=> Make ubuntu tests pass

attributes/default.rb, recipes/minimize_access.rb
Fedora tests should be fixed once dev-sec/linux-baseline#84 is merged.
CC @artem-sidorenko
=> Make fedora tests pass

.travis.yml, metadata.rb
Remove dependency on compat_resource (deprecated). Fixes #186, but may break older clients
=> Remove dependency on compat_resource

metadata.rb, recipes/sysctl.rb
and resolve the cleanup issue of old configs on our side
Fixes #192
=> Unpin sysctl dependency

.kitchen.yml, attributes/default.rb, metadata.rb, recipes/minimize_access.rb, recipes/packages.rb, recipes/selinux.rb, recipes/sysctl.rb
This PR adds support for Amazon Linux. The biggest change is the switch to the latest sysctl cookbook. This was pinned previously by @artem-sidorenko and discussed https://github.com/dev-sec/chef-os-hardening/issues/166#issuecomment-322433264
Are there any side-effects by moving to the latest version @artem-sidorenko ?
We may consider merging #193 first
Chef Omnibus install has an issue with Amazon Linux as described here https://github.com/chef/omnitruck/issues/346
=> add basic support for amazon linux

metadata.rb
The new major release 1.0.0 does not have recipes anymore, we will have
to reflect that. Pinning the major version for now.
=> Lazy pin the sysctl major version

.kitchen.dokken.yml, .kitchen.yml, .travis.yml
This builds on top of #194 and adds testing for Amazon Linux 1
=> improve testing around amazon linux

Gemfile
There's been a ton of bugfixes and improvements since 11.1.
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Test with Foodcritic 13

README.md, attributes/default.rb, recipes/login_defs.rb, spec/recipes/login_defs_spec.rb, templates/default/login.defs.erb
This change un-hardcodes the maximum user and group IDs assigned by useradd and groupadd respectively. Having them hardcoded can present problems for nodes that are configured with directory services (e.g. LDAP) and the range conflicts with IDs from there. These attributes will allow users to configure a non-conflicting ID range.
Signed-off-by: Matt Kulka <mkulka@parchment.com>
=> allow setting uid/gid max by attribute

.kitchen.do.yml, .kitchen.dokken.yml, .kitchen.yml, .travis.yml, Gemfile
Simplify the configs by using dokken images and bento slugs. Make sure to fail on deprecation warnings to keep the cookbook ready for upcoming chef releases. Also add testing of Debian 9 / Ubuntu 18.04 and remove EOL Debian 7
=> Update kitchen config for more platforms

.kitchen.dokken.yml
Missing renaming of platform for dokken
=> Fix Fedora EOL

recipes/pam.rb
On Debian-based distros, pam-auth-update is located at /usr/sbin/pam-auth-update. However, when running chef-client as a cron job, /usr/sbin may not be available on the path, resulting in an error. This affects nodes using the Azure Chef extension, among others.
Fixes #237
=> Use full path for executing pam-auth-update

attributes/sysctl.rb
Per Oracle support notes, exec-shield was removed from UEK. 
I am having a hard time testing this update since it requires much older versions of Chef libraries and is using older Rubocop settings. If there is documentation on testing specifically with Chef 12, feel free to point me in that direction.
This addresses #234 and if possible it would be great to include in #233
=> Do not apply exec-shield if running Oracle Linux with UEK - addresses #234

README.md, metadata.rb, recipes/sysctl.rb, spec/recipes/sysctl_spec.rb
Sysctl cookbook is deprecated and resource has been integrated to Chef as of 14.0.
=> Remove sysctl cookbook dependency and use new native sysctl resource

.kitchen.do.yml, .kitchen.dokken.yml, .kitchen.yml, .travis.yml
and switching Fedora 29 as current latest release
=> Removal of fedora 27 as its EOL

attributes/default.rb, templates/default/rhel_system_auth.erb
allow changing pam_unix.so options excluding sha512
I have a requirement to be able to set `remember=7` which currently cant be changed.
=> expose pam_unix.so options to an attribute

.github/workflows/test.yml
=> CI: disable debian-9 dokken tests for now

README.md, spec/spec_helper.rb
somehow it's broken and not clear if we really need it for stuff like automation code, especially with focus in test-kitchen testing
=> Removing coveralls

.github/workflows/test.yml
most likely the dokken tests are blocked because of this limitation
=> CI: run for all PRs
