dev-sec/chef-os-hardening

- attributes/sysctl.rb
- settings are defined in our tests: https://github.com/hardening-io/tests-os-hardening/pull/29
> feature: implement ipv6 router advertisement settings

- attributes/default.rb
- recipes/login_defs.rb
- templates/default/login.defs.erb
This allows the system uid/gid min/max to be configured
> Allow sys uid min/max and sys gid min/max to be configured

- .kitchen.yml
- Gemfile
changed gemfile to add inspec support and add the inspec verifier to kitchen.yml
> added inspec to gemfile and inspec verifier to kitchen.yml

- recipes/pam.rb
Howdy. Here's my pull request implementing a fix re: https://github.com/hardening-io/chef-os-hardening/issues/102
Please test, and let me know if you need more work to make this a good PR! Thanks!
Jesse
> Enable pam_pwquality in rhel-family > 7

- attributes/sysctl.rb
> Enable martian logging for ipv4

- .kitchen.vagrant.yml
- .kitchen.yml
- Gemfile
- README.md
- gemfile.chef-11
- depends on #116 
- uses kitchen-dokken in travis
- update vagrant boxes
> Use new InSpec integration tests

- metadata.rb
as currently this version looks broken to some tools and master
branch can not be used for instance via berkshelf
> Fix the version in metadata.rb

- .kitchen.vagrant.yml
- README.md
Switching all boxes to the bento (its maintained)
> Update of kitchen vagrant file

- Gemfile
- libraries/gpgcheck.rb
- recipes/suid_sgid.rb
and some rubocop/foodcritic fixes
> Update of Gemfile

- CHANGELOG.md
- Rakefile
I would merge this after successful CI run, then tag and release the 2.0.0
> Changelog for 2.0.0

- README.md
> Docs: fix the wrong kitchen URL and add inspec

- attributes/default.rb
- recipes/auditd.rb
> Support auditd installation on different distros

- recipes/limits.rb
- recipes/profile.rb
- spec/recipes/limits_spec.rb
- spec/recipes/profile_spec.rb
Fixes https://github.com/dev-sec/chef-os-hardening/issues/165
> Enable core dumps if they are enabled via attribute

- test/integration/default/controls/tests.rb
We do not have implementation for them within this cookbook yet
> Skip auditd tests

- .kitchen.do.local.yml
- .kitchen.yml
- .travis.yml
Fixes to get Fedora green will be done in a dedicated PR
> Fedora 25 is EOL, replacing with 27

- .travis.yml
Signed-off-by: Tim Smith <tsmith@chef.io>
> Test on Ruby 2.4.4

- .kitchen.yml
- Berksfile
- test/fixtures/cookbooks/test/metadata.rb
- test/fixtures/cookbooks/test/recipes/default.rb
The package lists of debian 9 DO image are not full/complete,
we updating them via test cookbook
> Fixing debian-9 CI tests

- .travis.yml
Fixup for #218, use newer fedora version in the CI
> Fix fedora EOL in the CI

- Gemfile
cucumber 4 fails in the CI:
https://travis-ci.org/dev-sec/chef-os-hardening/jobs/437063560
> Fix CI: pin cucumber 3

- .travis.yml
- README.md
Update README.md to include support for Ubuntu 18.04.
> Ubuntu 18.04 is supported

- .travis.yml
- removal of deprecated Travis settings
- removal of obsolete bug fix
> Update the CI settings - this fixes it again

- .kitchen.do.yml
- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
> Removal of Debian 8 as its EOL

- .kitchen.do.yml
- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
it gets EOL in couple of weeks
> Removal of Ubuntu 14.04 support

- README.md
> Docs: update of supported distros

- .kitchen.yml
- .travis.yml
- README.md
accepting the Chef EULA as non-commercial project
> Fix CI: run testing on Chef 14 and 15

- .kitchen.do.yml
- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
Signed-off-by: Artem Sidorenko <artem.sidorenko@t-systems.com>
> CI: testing of Debian 10

- .kitchen.do.yml
- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
Signed-off-by: Artem Sidorenko <artem.sidorenko@t-systems.com>
> CI: testing of Centos 8

- attributes/default.rb
- recipes/auditd.rb
- templates/default/auditd.conf.erb
- test/integration/default/controls/tests.rb
rebase of the work done by @artem-sidorenko on #182
> Initial (sans Arch) auditd management support.

- recipes/minimize_access.rb
> Fix warning on managing /bin/su symlink

- Rakefile
- recipes/minimize_access.rb
Signed-off-by: Math Fortin <mathieu@fortin.info>
This PR is to address issue #272
> Resolving os-13 validation from linux-baseline

- .github/workflows/test.yml
- .kitchen.dokken.yml
- .kitchen.yml
let's have the old vagrant way, some people might still use it
> Kitchen: vagrant and dokken tests

- .github/workflows/test.yml
- .kitchen.do.yml
- .kitchen.dokken.yml
- .kitchen.yml
- README.md
- test/integration/default/controls/tests.rb
for now without new distro versions
> CI: tests on the real DO VMs

- .github/workflows/test.yml
> CI: another catch-all job for runs on the main code

- .github/workflows/test.yml
- we would see the test results for releases too
- we would get our release placeholder final job
> CI: run the test workflow also on the release branches
